### ISSUE TITLE
New release to PyPI

### ISSUE THREAD

**Issue by Qbicz** [apmorton/pyhidapi#27]
Hi!

A new release to pip would be really welcome, especially with the fix from 30 Apr https://github.com/apmorton/pyhidapi/commit/ea1eafd9175b25f9fd6d8bbc0ed5c27fe023abd9 which fixes segmentation fault on 64-bit machines.

**Comment by apmorton** [comment]
https://pypi.org/project/hid/1.0.3/

Has been on pypi since June 6th

**Comment by Qbicz** [comment]
Thanks! What about https://pypi.org/project/pyhidapi/ ? It is the first result when you google for "pyhidapi".

**Comment by apmorton** [comment]
Unfortunately named, but unrelated to this project - take a look at where the project homepage takes you. It does also appear to be a relatively new addition to pypi, in only 2018, even though the project homepage shows it being from much longer ago.

There also exists "hidapi" here: https://pypi.org/project/hidapi/ which is also unrelated to this project.

Perhaps a direct link to the pypi page and "pip install hid" section in the readme wouldn't be a bad idea.
