### ISSUE TITLE
tag pypi releases on GitHub

### ISSUE THREAD

**Issue by colemickens** [apmorton/pyhidapi#37]
Hi. For `nixpkgs` (https://github.com/nixos/nixpkgs) ([repology](https://repology.org/repository/nix_unstable)) we like to pull the source directly, rather than from GitHub. Ideally we are able to pull tagged releases that much the package version.

Would it be possible to have the pypi releases tagged here? Thanks!

**Comment by apmorton** [comment]
I have now tagged all previous pypi releases on github
