### ISSUE TITLE
Python 2 TypeError: one character string expected

### ISSUE THREAD

**Issue by anton-dos** [apmorton/pyhidapi#46]
Erorr in 'get_feature_report' function:
data[0] = bytearray((report_id,))

struct.pack('B', report_id) instead bytearray((report_id,)) is a suitable solution for both python versions

**Comment by elfmimi** [comment]
P-R https://github.com/apmorton/pyhidapi/pull/43 is addressing the same issue.

**Comment by apmorton** [comment]
https://www.python.org/doc/sunset-python-2/
