### ISSUE TITLE
still get error with hid_get_input_report when using 1.0.5

### ISSUE THREAD

**Issue by allenz92** [apmorton/pyhidapi#54]
Ubuntu 20.04.4 LTS
python3.8

root@jmx-desktop:/home/jmx# pip list | grep hid
hid                    1.0.5

Here is my stack trace:

 import hid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/hid/__init__.py", line 83, in <module>
    hidapi.hid_get_input_report.argtypes = [ctypes.c_void_p, ctypes.c_char_p, ctypes.c_size_t]
  File "/usr/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib/aarch64-linux-gnu/libhidapi-hidraw.so.0: undefined symbol: hid_get_input_report

**Comment by apmorton** [comment]
This indicates your version of the native libhidapi is too old.

hid_get_input_report is a fairly recent addition to libhidapi, so it isn't surprising.

You need to update your native library, and then pyhidapi should work.

**Comment by mike-lawrence** [comment]
@allenz92 If you're on 20.04, then apt is serving you version 0.9 of libhidapi. I'm still working out myself whether it's possible to pull a newer version or build it from source, or if I'll need to fully upgrade to 22.04 to get it.
