### ISSUE TITLE
h.write what does returned value represent?

### ISSUE THREAD

**Issue by Thriftguy** [apmorton/pyhidapi#57]
What does the returned 130 value mean?
>>> h.open(1410,5921)
>>> h.write(b'\x0A\x00\x00\x00')
130

if I run it again without closing the port it will return -1 like below, my code works I just dont know what the returned values means if someone can tell me that knows, thanks.

>>> h.write(b'\x00\x00\x00\x00')
130
>>> h.write(b'\x00\x00\x00\x00')
-1

**Comment by apmorton** [comment]
Can you show more of your example code? I'm not sure, because this library doesn't have any function named `open`.

**Comment by Thriftguy** [comment]
you can type it interactively into the python repl and get the same return
first
import hid
then import pprint <--- maybe it is returning from this perhaps?
then use pprint to enumerate and show hid devices
then define the vid and pid
then I define h as hid.device
then h.open(vid, pid)
then h.write my command and it returns like above

**Comment by apmorton** [comment]
Can you:
```
import hid
print(hid)
```

I'm pretty sure you are using another library: https://github.com/trezor/cython-hidapi

As stated, this library does not have any function named `open`

**Comment by Thriftguy** [comment]
>>> import hid
>>> print(hid)
<module 'hid' from 'c:\\users\\thriftguy\\cython-hidapi\\hid.cp36-win_amd64.pyd'>
>>>
I see it in the help file now it states
hid.write() will send the data on the first OUT endpoint, if one exists. If it does not, it will send the data through the Control Endpoint (Endpoint 0).

device must be an opaque external reference to a device. data must be a Buffer that data is read from.

This function returns the actual number of bytes written, or throws an error.


is that not this hid repo?

**Comment by apmorton** [comment]
You are using https://github.com/trezor/cython-hidapi

**Comment by Thriftguy** [comment]
Thanks sorry to bother, when I clicked on homepage it redirected me to this repo
