### ISSUE TITLE
Read core dumps on Fedora 23 64-bit

### ISSUE THREAD

**Issue by wadester** [apmorton/pyhidapi#7]
Freshly installed Fedora 23 on old Lenovo core2 laptop
Installed hid-0.1.1 (python setup.py install)
Connected USB mouse with receiver (Logitech wireless with receiver)
Changed permissions on /dev/hid\*  for testing (chmod 777 /dev/hidraw*)
Ran hid_test.py (script referenced in previous issue)
Python dumped core when trying to read HID events

$ ./hid_test.py 
HID info= [{'usage_page': 61376, 'product_id': 50459, 'interface_number': 0, 'manufacturer_string': u'Logitech', 'vendor_id': 1133, 'release_number': 17920, 'serial_number': u'', 'usage': 2335, 'path': '/dev/hidraw0', 'product_string': u'USB Receiver'}, {'usage_page': 32, 'product_id': 50459, 'interface_number': 1, 'manufacturer_string': u'Logitech', 'vendor_id': 1133, 'release_number': 17920, 'serial_number': u'', 'usage': 0, 'path': '/dev/hidraw1', 'product_string': u'USB Receiver'}]
Path=/dev/hidraw0 Vid=1133 Pid=50459

With Python debugger, single stepping:

> /usr/lib/python2.7/site-packages/hid-0.1.1-py2.7.egg/hid/**init**.py(95)**hidcall()
> -> def __hidcall(self, function, _args, *_kwargs):
> (Pdb) s
> /usr/lib/python2.7/site-packages/hid-0.1.1-py2.7.egg/hid/__init**.py(96)**hidcall()
> -> if self.__dev == 0:
> (Pdb) s
> /usr/lib/python2.7/site-packages/hid-0.1.1-py2.7.egg/hid/__init**.py(99)__hidcall()
> -> ret = function(_args, *_kwargs)
> (Pdb) s
> Segmentation fault (core dumped)

Fedora 23 includes the following library:   hidapi-0.7.0-5.a88c724.fc23.x86_64

**Comment by apmorton** [comment]
I can only speculate from python debugger output - can you upload an actual core dump somewhere for me to look at?

**Comment by wadester** [comment]
I'll generate one tonight and send it to you.

Thanks,
--
Wade Hampton

**Comment by wadester** [comment]
I have a core file.  I had to use sysctl as I'm not sure where Fedora is
putting core files these days....

See attached,
--
Wade Hampton

**Comment by apmorton** [comment]
looks like github doesn't process email attachments - you will need to upload it manually on the site.

**Comment by wadester** [comment]
Sorry, can't upload a core file as Github complains.  Pls send me your e-mail offline and I'll send it directly to you.

From Github:  "Unfortunately, we don’t support that file type. ￼ Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, or PDF."

**Comment by 3demax** [comment]
@wadester May I advise you using https://gist.github.com/ ?
With this, you can create almost empty gist (which is actually a git repository) and `git push` whatever you need to.
