### ISSUE TITLE
Missing hid_error() return type declaration

### ISSUE THREAD

**Issue by Nicolasp38** [apmorton/pyhidapi#9]
hid_error() return type is not specified.
The following line has to be added (at line 60) :
hidapi.hid_error.restype = ctypes.c_wchar_p

**Comment by apmorton** [comment]
@Nicolasp38 I don't currently have anything to test this fix with, so if you could please give the latest master a try and confirm it is working properly I will increment the version number and publish it to pypi.

Thanks for reporting this issue.

Austin

**Comment by Nicolasp38** [comment]
This is ok for me.
